// This application's fonts.
//
// Both kinds of atlas under src/fonts/ were generated by `npm run gen:fonts` into
// packages/scripts/out/ and copied here by hand. That copy is the point: the generator writes
// to its own output folder and stops, and an atlas becomes an application's asset the moment
// the developer decides which faces the application actually draws with. Regenerating does not
// silently change what ships.
//
//   msdf/       one PNG + metrics JSON per style - what `Text` samples
//   polygons/   one JSON per style, glyph outlines as data - what `VectorText` tessellates
//
// The engine ships an Inter MSDF atlas of its own, and passing MSDF_ATLASES below is what
// overrides it. Doing so is not strictly necessary here - the fallback IS Inter, so the pixels
// would be identical - but relying on it would mean this app never exercises the path every
// real application takes, and would leave the choice of typeface to the renderer.
//
// Neither kind is bundled into the JS. The PNGs and the outline atlases come in as `?url` and
// are fetched; only the small MSDF metrics JSON is inlined, because the shaper needs it
// synchronously to lay out a line.

import { PolygonFontBook, type MsdfAtlasSource, type PolygonFontJson, type PolygonFontSource, type FontStyle } from '@mvpaint/engine'

import interRegularMetrics from './msdf/inter-regular.json'
import interBoldMetrics from './msdf/inter-bold.json'
import interItalicMetrics from './msdf/inter-italic.json'
import interBoldItalicMetrics from './msdf/inter-bold-italic.json'

import interRegularPng from './msdf/inter-regular.png?url'
import interBoldPng from './msdf/inter-bold.png?url'
import interItalicPng from './msdf/inter-italic.png?url'
import interBoldItalicPng from './msdf/inter-bold-italic.png?url'

import interRegularPolygons from './polygons/inter-regular.polygons.json?url'
import interBoldPolygons from './polygons/inter-bold.polygons.json?url'
import interItalicPolygons from './polygons/inter-italic.polygons.json?url'
import interBoldItalicPolygons from './polygons/inter-bold-italic.polygons.json?url'

/**
 * The MSDF atlases, handed to `createSceneRenderer({ fonts })` - see WebGPUCanvas.tsx.
 *
 * The `as unknown as` is the generated JSON meeting the type it was generated for: a bundler
 * types an imported document by its literal contents, which is a much narrower type than
 * MsdfFontJson and not assignable to it.
 */
export const MSDF_ATLASES: readonly MsdfAtlasSource[] = [
  { style: 'regular', url: interRegularPng, json: interRegularMetrics as unknown as MsdfAtlasSource['json'] },
  { style: 'bold', url: interBoldPng, json: interBoldMetrics as unknown as MsdfAtlasSource['json'] },
  { style: 'italic', url: interItalicPng, json: interItalicMetrics as unknown as MsdfAtlasSource['json'] },
  { style: 'bold-italic', url: interBoldItalicPng, json: interBoldItalicMetrics as unknown as MsdfAtlasSource['json'] },
]

const POLYGON_URLS: Readonly<Record<FontStyle, string>> = {
  regular: interRegularPolygons,
  bold: interBoldPolygons,
  italic: interItalicPolygons,
  'bold-italic': interBoldItalicPolygons,
}

let pending: Promise<PolygonFontBook> | null = null

/**
 * Fetch the outline atlases into a PolygonFontBook - what a `VectorText` node is constructed
 * with. Nothing in the engine does this for you: outlines are supplied per node, through the
 * VectorFonts interface, and this is the application's side of it.
 *
 * Lazy, because these files are the whole cost of the vector path and the scenes that draw MSDF
 * text should not pay it. Memoized on the promise rather than the result, so several scenes
 * loading at once share one set of fetches instead of racing.
 */
export function loadVectorFonts(): Promise<PolygonFontBook> {
  if (!pending) {
    pending = Promise.all(
      (Object.keys(POLYGON_URLS) as FontStyle[]).map(async (style): Promise<PolygonFontSource> => {
        const response = await fetch(POLYGON_URLS[style])
        if (!response.ok) throw new Error(`Failed to load the ${style} glyph atlas (${response.status})`)
        return { style, json: (await response.json()) as PolygonFontJson }
      }),
    )
      .then((sources) => new PolygonFontBook(sources))
      .catch((error: unknown) => {
        // Don't cache a failure - a transient network error shouldn't disable the vector text
        // path for the rest of the session.
        pending = null
        throw error
      })
  }
  return pending
}
