// This application's fonts.
//
// Both kinds of atlas were generated by `npm run gen:fonts` into packages/scripts/out/ and
// copied into public/fonts/ by hand. That copy is the point: the generator writes to its own
// output folder and stops, and an atlas becomes an application's asset the moment the developer
// decides which faces the application actually draws with. Regenerating does not silently change
// what ships.
//
//   public/fonts/msdf/       one PNG + metrics JSON per style - what `MSDFText` samples
//   public/fonts/polygons/   one JSON per style, glyph outlines as data - what `VectorText`
//                            tessellates
//
// PUBLIC, NOT src. Nothing here is imported into the bundle: every file is fetched at runtime
// from a URL, and Vite copies public/ into dist/ verbatim on build. The engine ships no
// typeface, so an application's fonts are data it serves. public/ and a CSP-approved CDN are
// the two ways to serve them and differ only in what BASE below resolves to; either way an
// atlas can be replaced without rebuilding the application.
//
// This puts one round trip before the first frame of text: the metrics JSON has to be in hand
// before the renderer is created, because the shaper measures with it synchronously. See
// loadMsdfAtlases below and its one caller, WebGPUCanvas.tsx.

import { PolygonFontBook, type MsdfAtlasSource, type MsdfFontJson, type PolygonFontJson, type PolygonFontSource, type FontStyle } from '@mvpaint/engine'

/**
 * Where public/ is served from. `import.meta.env.BASE_URL` is '/' on the dev server and './'
 * for the production build (see vite.config.ts, which uses a relative base so a GitHub Pages
 * project site works without hardcoding the repo name). Point it at a CDN origin instead and
 * nothing else in this file changes.
 */
const BASE = import.meta.env.BASE_URL

const STYLES: readonly FontStyle[] = ['regular', 'bold', 'italic', 'bold-italic']

/** `bold-italic` -> `<base>fonts/msdf/inter-bold-italic.png`, and so on. */
const msdfUrl = (style: FontStyle, ext: 'png' | 'json') => `${BASE}fonts/msdf/inter-${style}.${ext}`
const polygonUrl = (style: FontStyle) => `${BASE}fonts/polygons/inter-${style}.polygons.json`

async function fetchJson<T>(url: string, what: string): Promise<T> {
  const response = await fetch(url)
  // Vite's dev server answers a missing public/ file through the SPA fallback: index.html,
  // with a 200. The content type is the check that catches it, so both it and the status are
  // tested here.
  if (!response.ok) throw new Error(`Failed to load ${what} (${response.status} from ${url})`)
  const type = response.headers.get('content-type') ?? ''
  if (!type.includes('json')) throw new Error(`${url} returned ${type || 'no content type'}, not JSON - is ${what} missing from public/?`)
  return (await response.json()) as T
}

let msdfPending: Promise<readonly MsdfAtlasSource[]> | null = null
let msdfLoaded: readonly MsdfAtlasSource[] | null = null

/**
 * The MSDF atlases, handed to `createSceneRenderer({ fonts })` - see WebGPUCanvas.tsx.
 *
 * Only the metrics are fetched here. Each source carries a URL for its PNG and the engine
 * fetches those itself, straight into a texture, so the four images never pass through this
 * module or the JS heap.
 *
 * Memoized on the promise rather than the result, so a remount mid-flight shares one set of
 * fetches. A failure clears the memo, so the next call retries.
 */
export function loadMsdfAtlases(): Promise<readonly MsdfAtlasSource[]> {
  if (!msdfPending) {
    msdfPending = Promise.all(
      STYLES.map(async (style): Promise<MsdfAtlasSource> => {
        const json = await fetchJson<MsdfFontJson>(msdfUrl(style, 'json'), `the ${style} MSDF metrics`)
        return { style, url: msdfUrl(style, 'png'), json }
      }),
    )
      .then((sources) => {
        msdfLoaded = sources
        return sources
      })
      .catch((error: unknown) => {
        msdfPending = null
        throw error
      })
  }
  return msdfPending
}

/**
 * The atlases, synchronously, for code that runs after they are in hand and cannot await -
 * scene builders, which the engine's contract makes synchronous (see scenes/types.ts).
 *
 * Held on the side rather than threaded through the scene contract, the same way
 * vectorTextStressScene holds its parsed outlines. The canvas awaits loadMsdfAtlases() before
 * it creates the renderer, and no scene builds before the renderer exists, so this is
 * populated by the time any caller reaches it. The throw below states that ordering.
 */
export function msdfAtlases(): readonly MsdfAtlasSource[] {
  if (!msdfLoaded) throw new Error('The MSDF atlases have not been loaded yet - await loadMsdfAtlases() first.')
  return msdfLoaded
}

let polygonPending: Promise<PolygonFontBook> | null = null

/**
 * Fetch the outline atlases into a PolygonFontBook - what a `VectorText` node is constructed
 * with. Nothing in the engine does this for you: outlines are supplied per node, through the
 * VectorFonts interface, and this is the application's side of it.
 *
 * Lazy: these files belong to the vector path alone, so a scene drawing MSDF text never
 * requests them. Memoized the same way as the atlases above.
 */
export function loadVectorFonts(): Promise<PolygonFontBook> {
  if (!polygonPending) {
    polygonPending = Promise.all(
      STYLES.map(async (style): Promise<PolygonFontSource> => {
        const json = await fetchJson<PolygonFontJson>(polygonUrl(style), `the ${style} glyph atlas`)
        return { style, json }
      }),
    )
      .then((sources) => new PolygonFontBook(sources))
      .catch((error: unknown) => {
        polygonPending = null
        throw error
      })
  }
  return polygonPending
}
