// This application's fonts.
//
// Both kinds of atlas were generated by `npm run gen:fonts` into packages/scripts/textgen/out/ and
// copied into public/fonts/ by hand. That copy is the point: the generator writes to its own
// output folder and stops, and an atlas becomes an application's asset the moment the developer
// decides which faces the application actually draws with. Regenerating does not silently change
// what ships.
//
//   public/fonts/msdf/       one PNG + metrics JSON per style - what `MSDFText` samples
//   public/fonts/polygons/   one JSON per style, glyph outlines as data - what `VectorText`
//                            tessellates
//
// PUBLIC, NOT src. Nothing here is imported into the bundle: every file is fetched at runtime
// from a URL, and Vite copies public/ into dist/ verbatim on build. The engine ships no
// typeface, so an application's fonts are data it serves. public/ and a CSP-approved CDN are
// the two ways to serve them and differ only in what BASE below resolves to; either way an
// atlas can be replaced without rebuilding the application.
//
// This puts one round trip before the first frame of text: the metrics JSON has to be in hand
// before the renderer is created, because the shaper measures with it synchronously. See
// loadMsdfAtlases below and its one caller, WebGPUCanvas.tsx.
//
// WHAT THIS FILE IS NOW: addresses, and nothing else. The fetching, the JSON content-type check
// that catches a dev server answering a missing file with index.html, and the memo that keeps a
// remount mid-flight from fetching twice all live in the engine (resources/fontSources.ts),
// keyed on these URLs. Two applications asking for the same face share one fetch; asking again
// after a switch costs nothing.

import {
  DEFAULT_FONT_FAMILY,
  loadFontFamily,
  loadMsdfAtlases as loadMsdfAtlasesFrom,
  registerFontFamily,
  vectorFontsFor,
  type MsdfAtlasSource,
  type FontStyle,
} from '@mvpaint/engine'

/**
 * The name this application's typeface is registered under, and what every text node names.
 *
 * One name for both kinds of text: an `MSDFText` samples the distance-field atlases and a
 * `VectorText` tessellates the outlines, and both say `fontFamily: INTER` to mean Inter.
 */
export const INTER = 'inter'

/**
 * Where public/ is served from. `import.meta.env.BASE_URL` is '/' on the dev server and './'
 * for the production build (see vite.config.ts, which uses a relative base so a GitHub Pages
 * project site works without hardcoding the repo name). Point it at a CDN origin instead and
 * nothing else in this file changes.
 */
const BASE = import.meta.env.BASE_URL

const STYLES: readonly FontStyle[] = ['regular', 'bold', 'italic', 'bold-italic']

/** `bold-italic` -> `<base>fonts/msdf/inter-bold-italic.png`, and so on. */
const msdfUrl = (style: FontStyle, ext: 'png' | 'json') => `${BASE}fonts/msdf/inter-${style}.${ext}`
const polygonUrl = (style: FontStyle) => `${BASE}fonts/polygons/inter-${style}.polygons.json`

let msdfLoaded: readonly MsdfAtlasSource[] | null = null

/**
 * The MSDF atlases, handed to `createSceneRenderer({ fonts })` - see WebGPUCanvas.tsx.
 *
 * Only the metrics are fetched. Each source carries a URL for its PNG and the engine fetches
 * those itself, straight into a texture, so the four images never pass through this module or
 * the JS heap.
 *
 * Never released: a typeface is loaded before the first frame of text and drawn from until the
 * page goes, so there is no moment at which letting go of it is the right thing.
 */
export async function loadMsdfAtlases(): Promise<readonly MsdfAtlasSource[]> {
  const loaded = await loadMsdfAtlasesFrom(
    STYLES.map((style) => ({ style, metricsUrl: msdfUrl(style, 'json'), imageUrl: msdfUrl(style, 'png') })),
  )
  msdfLoaded = loaded.sources
  return loaded.sources
}

/**
 * The atlases, synchronously, for code that runs after they are in hand and cannot await -
 * scene builders, which the engine's contract makes synchronous (see scenes/types.ts).
 *
 * Held on the side rather than threaded through the scene contract, the same way
 * vectorTextStressScene holds its parsed outlines. The canvas awaits loadMsdfAtlases() before
 * it creates the renderer, and no scene builds before the renderer exists, so this is
 * populated by the time any caller reaches it. The throw below states that ordering.
 */
export function msdfAtlases(): readonly MsdfAtlasSource[] {
  if (!msdfLoaded) throw new Error('The MSDF atlases have not been loaded yet - await loadMsdfAtlases() first.')
  return msdfLoaded
}

/**
 * Fetch the outline atlases and register them under `INTER`, so every `VectorText` naming that
 * family can draw. Nothing is handed back: a node names a font, it is not given one.
 *
 * Lazy: these files belong to the vector path alone, so a scene drawing MSDF text never requests
 * them. Held for the life of the page, like the atlases above, so the book is never released.
 */
export async function loadVectorFonts(): Promise<void> {
  await loadFontFamily(INTER, { vector: STYLES.map((style) => ({ style, url: polygonUrl(style) })) })
  // Registered under the default name as well, pointing at the same book, so a VectorText that
  // names no family draws - exactly as an MSDFText that names none does. Two entries, one book.
  const book = vectorFontsFor(INTER)
  if (book) registerFontFamily(DEFAULT_FONT_FAMILY, { vector: book })
}
