// Self-test for the runtime font parser: outline extraction from raw command streams, and
// TtfFont against the real Inter TTFs.
//
// These used to live in the engine, because the parser did. They moved out with it, and what
// they check moved with them: that a font file becomes the same metrics and the same outlines
// the engine's own polygon atlas carries. The comparison is deliberate - the atlas is
// generated by this code (see packages/scripts/text/polygon), so if the two ever disagree,
// every application drawing vector text is drawing something the tests never saw.
//
// No GPU and no DOM: the parser and the geometry are both pure. Run with:
//   npx vitest run packages/ttf/src/ttf.test.ts

import { expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { kerningFor, type MsdfFontJson } from '@mvpaint/engine/src/text/msdfMetrics'
import { contoursFromCommands } from './glyphOutline'
import { TtfFontBook, TtfFont } from './TtfFont'
import regularJson from '@mvpaint/engine/src/text/fonts/inter-regular.json'
import regularPolygons from '@mvpaint/engine/src/text/fonts/inter-regular.polygons.json'

/**
 * Every check in this file goes through here, so each one reads as the sentence it is making
 * and vitest reports that sentence when it stops being true.
 */
function assert(cond: boolean, msg: string): void {
  expect(cond, msg).toBe(true)
}

const ttf = (name: string): ArrayBuffer => {
  const bytes = readFileSync(new URL(`../../scripts/fonts/${name}`, import.meta.url))
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer
}

it('contour extraction from raw command streams (no font file involved)', () => {
    // Fonts store y up; opentype hands paths back y-down, so every y is negated on the way in.
    const tri = contoursFromCommands(
      [
        { type: 'M', x: 0, y: 0 },
        { type: 'L', x: 100, y: 0 },
        { type: 'L', x: 0, y: -100 },
        { type: 'Z' },
      ],
      1,
    )
    assert(tri.length === 1, 'a closed triangle yields one contour')
    assert(tri[0].closed === true, 'the contour is closed')
    assert(tri[0].points.length === 3, 'three corners, with no repeat of the start point')
    assert(tri[0].points[2].y === 100, "opentype's y-down coordinates are flipped to y-up")

    // A moveto immediately followed by a lineto to the same point is common in real fonts,
    // and a zero-length edge breaks contour classification (see glyphOutline.ts).
    const deduped = contoursFromCommands(
      [
        { type: 'M', x: 10, y: 10 },
        { type: 'L', x: 10, y: 10 },
        { type: 'L', x: 90, y: 10 },
        { type: 'L', x: 90, y: 90 },
        { type: 'L', x: 10, y: 10 },
        { type: 'Z' },
      ],
      1,
    )
    assert(deduped.length === 1, 'the degenerate edges still leave one contour')
    assert(deduped[0].points.length === 3, 'duplicate and wrap-around points are dropped')

    // Curves subdivide; a tighter tolerance subdivides further.
    const quad = (tolerance: number) =>
      contoursFromCommands(
        [
          { type: 'M', x: 0, y: 0 },
          { type: 'Q', x1: 50, y1: -100, x: 100, y: 0 },
          { type: 'Z' },
        ],
        tolerance,
      )
    const coarse = quad(20)
    const fine = quad(0.5)
    assert(coarse[0].points.length >= 3, 'a quadratic flattens to a usable ring')
    assert(fine[0].points.length > coarse[0].points.length, 'a tighter tolerance subdivides more')

    // Anything that can't enclose an area isn't a fillable contour.
    assert(contoursFromCommands([{ type: 'M', x: 0, y: 0 }, { type: 'L', x: 5, y: 0 }, { type: 'Z' }], 1).length === 0, 'a two-point ring is dropped')
    assert(contoursFromCommands([], 1).length === 0, 'an empty command stream yields no contours')
})

//
// This is the one thing a parser does that an atlas cannot: a font has thousands of glyphs and
// a label uses a dozen, so nothing is measured until some text asks for it.
it('glyphs and kerning are measured on demand, not up front', async () => {
    const font = (await TtfFontBook.load([{ style: 'regular', data: ttf('Inter-Regular.ttf') }])).fontByIndex(0)!
    assert(font.metrics.glyphs.size === 0, 'a freshly parsed font has measured nothing')
    font.ensure('Ao ')
    assert(font.metrics.glyphs.size === 3, 'ensure() measures exactly the characters asked for')
    assert(font.metrics.glyphs.has(65) && font.metrics.glyphs.has(111) && font.metrics.glyphs.has(32), 'A, o and space are all present')

    // A blank glyph has no box but still advances the pen - otherwise spaces would collapse.
    const space = font.metrics.glyphs.get(32)!
    assert(space.width === 0 && space.height === 0, 'space has no outline extents')
    assert(space.xadvance > 0, 'space still advances')

    // A code point the font has no glyph for is measured once and left absent, so the shaper
    // spaces it exactly as an atlas does for a character outside its charset.
    font.ensure('\u{1F600}')
    assert(!font.metrics.glyphs.has(0x1f600), 'an unmapped code point stays absent rather than becoming tofu')
    assert(font.mesh(0x1f600) === undefined, 'and has no mesh')
    assert(!font.hasGlyph(0x1f600) && font.hasGlyph(65), 'hasGlyph answers the same question without measuring')
})

it('kerning comes from GPOS, which needs the positioning engine initialized', async () => {
    const pair = (regularJson as unknown as MsdfFontJson).kernings.find((k) => k.amount !== 0)!
    const font = (await TtfFontBook.load([{ style: 'regular', data: ttf('Inter-Regular.ttf') }])).fontByIndex(0)!
    font.ensure(String.fromCodePoint(pair.first) + String.fromCodePoint(pair.second))
    const mine = kerningFor(font.metrics, pair.first, pair.second) / font.metrics.size
    assert(mine !== 0, 'GPOS kerning is found (the positioning engine was initialized)')
    // The MSDF atlas stores kerning as whole pixels at its 42px generation size, so the two
    // agree only up to that quantization - compare on the atlas's own grid rather than in em.
    const msdfSize = (regularJson as unknown as MsdfFontJson).info.size
    assert(Math.abs(mine * msdfSize - pair.amount) <= 0.75, 'the kerning amount matches the MSDF metrics, up to its pixel rounding')
})

it('cached glyph meshes, and the same geometry the polygon atlas ships', async () => {
    const book = await TtfFontBook.load([{ style: 'regular', data: ttf('Inter-Regular.ttf') }])
    const font = book.fontByIndex(0)!
    font.ensure('oI ')

    const o = font.mesh(111)!
    assert(o.contours.length === 2, "'o' has an outer ring and a counter")
    assert(o.vertices.length > 0 && o.indices.length % 3 === 0, 'the counter is triangulated into whole triangles')
    assert(font.mesh(111) === o, 'a glyph mesh is built once and cached')
    assert(font.mesh(73)!.contours.length === 1, "'I' is a single ring")

    // Whitespace resolves to a real glyph with no outline - not a miss, which would make the
    // shaper fall back to a space's advance instead of using the space's own.
    const space = font.mesh(32)!
    assert(space.contours.length === 0 && space.vertices.length === 0, 'space has a mesh with no geometry')

    // The committed atlas was generated from this same font by this same code, so a live parse
    // has to reproduce it - to the whole font unit the atlas is quantized at. This is what makes
    // the two paths substitutable: an application that swaps the atlas for a runtime parse gets
    // the same letterforms, not merely similar ones.
    const atlas = regularPolygons as unknown as {
      unitsPerEm: number
      glyphs: { codePoint: number; advance: number; rings?: number[][] }[]
    }
    assert(atlas.unitsPerEm === font.unitsPerEm, 'the atlas is in the same unit system the parser reports')

    const shipped = new Map(atlas.glyphs.map((glyph) => [glyph.codePoint, glyph]))
    const sample = [111, 73, 65, 87, 38, 64, 37] // o I A W & @ %
    font.ensure(String.fromCodePoint(...sample))
    for (const codePoint of sample) {
      const char = String.fromCodePoint(codePoint)
      const baked = shipped.get(codePoint)!
      const live = font.contours(codePoint)!
      assert(baked.rings!.length === live.length, `${char}: the atlas has as many rings as a live parse`)
      baked.rings!.forEach((ring, i) => {
        assert(ring.length === live[i].points.length * 2, `${char}: ring ${i} has the same point count`)
        const worst = live[i].points.reduce(
          (max, point, j) => Math.max(max, Math.abs(ring[j * 2] - point.x), Math.abs(ring[j * 2 + 1] - point.y)),
          0,
        )
        assert(worst <= 0.5, `${char}: ring ${i} matches to within the atlas's rounding (off by ${worst.toFixed(3)})`)
      })
      assert(Math.abs(baked.advance - font.metrics.glyphs.get(codePoint)!.xadvance) <= 0.5, `${char}: same advance`)
    }
})

it('a book resolves styles, synthesizing what it was not given', async () => {
    const book = await TtfFontBook.load([
      { style: 'regular', data: ttf('Inter-Regular.ttf') },
      { style: 'bold', data: ttf('Inter-Bold.ttf') },
    ])
    assert(book.indexOf('italic') === 2, 'a style has its stable index whether or not it is loaded')

    const bold = book.resolve('bold')
    assert(bold.atlasIndex === 1 && !bold.fauxBold, 'a loaded style resolves to itself')

    const italic = book.resolve('italic')
    assert(italic.atlasIndex === 0 && italic.fauxItalic && !italic.fauxBold, 'a missing italic is faked from regular')

    const boldItalic = book.resolve('bold-italic')
    assert(boldItalic.atlasIndex === 1 && boldItalic.fauxItalic, 'bold-italic keeps the real bold and fakes the slant')

    // A book with no regular at all still resolves - to whatever it does have.
    const only = await TtfFontBook.load([{ style: 'bold', data: ttf('Inter-Bold.ttf') }])
    const fallback = only.resolve('regular')
    assert(fallback.atlasIndex === 1 && only.fontByIndex(1) !== undefined, 'a one-style book falls back to that style')

    // prepare() is how a VectorText measures before shaping; it must reach the resolved font.
    book.prepare('italic', 'Wave')
    assert(book.fontByIndex(0)!.metrics.glyphs.has(87), 'prepare measures into the font the style resolved to')
})

it('a curve tolerance that is coarser produces fewer points, and is honoured per book', async () => {
    const coarse = (await TtfFontBook.load([{ style: 'regular', data: ttf('Inter-Regular.ttf') }], { curveToleranceEm: 1 / 20 })).fontByIndex(0)!
    const fine = (await TtfFontBook.load([{ style: 'regular', data: ttf('Inter-Regular.ttf') }], { curveToleranceEm: 1 / 2000 })).fontByIndex(0)!
    coarse.ensure('o')
    fine.ensure('o')
    assert(coarse.mesh(111)!.contours[0].points.length < fine.mesh(111)!.contours[0].points.length, 'a tighter tolerance keeps more of the curve')
})

it('a buffer that is not a font is rejected, rather than half-parsed', async () => {
    let rejected = false
    try {
      await TtfFont.parse(new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]).buffer)
    } catch {
      rejected = true
    }
    assert(rejected, 'parsing something that is not a font throws')
})
